In [3]:
import numpy as np
import pandas as pd

In [5]:
df = pd.read_csv("../Documents/moviereviews.tsv",sep='\t')

In [7]:
df.head()

  label                                             review
0   neg  how do films like mouse hunt get into theatres...
1   neg  some talented actresses are blessed with a dem...
2   pos  this has been an extraordinary year for austra...
3   pos  according to hollywood movies made in last few...
4   neg  my first press screening of 1998 and already i...

In [11]:
df.dropna(inplace=True)

In [15]:
blanks = []
for i,lb,rv in df.itertuples():
    if type(rv) == str:
        if rv.isspace():
            blanks.append(i)

In [17]:
blanks

[57,
 71,
 147,
 151,
 283,
 307,
 313,
 323,
 343,
 351,
 427,
 501,
 633,
 675,
 815,
 851,
 977,
 1079,
 1299,
 1455,
 1493,
 1525,
 1531,
 1763,
 1851,
 1905,
 1993]

In [19]:
df.drop(blanks,inplace=True)

In [21]:
df['label'].value_counts()

label
neg    969
pos    969
Name: count, dtype: int64

In [86]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Engel\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [53]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [54]:
sid = SentimentIntensityAnalyzer()

In [55]:
df['scores'] = df['review'].apply(lambda review: sid.polarity_scores(review))

In [60]:
df['compound'] = df['scores'].apply(lambda d:d['compound'])

In [62]:
df['comp_score'] = df['compound'].apply(lambda score:'pos' if score >= 0 else 'neg')

In [64]:
df.head()

,label,review,scores,compound,comp_score
0,neg,how do films like mouse hunt get into theatres...,"{'neg': 0.121, 'neu': 0.778, 'pos': 0.101, 'co...",-0.9125,neg
1,neg,some talented actresses are blessed with a dem...,"{'neg': 0.12, 'neu': 0.775, 'pos': 0.105, 'com...",-0.8618,neg
2,pos,this has been an extraordinary year for austra...,"{'neg': 0.068, 'neu': 0.781, 'pos': 0.15, 'com...",0.9951,pos
3,pos,according to hollywood movies made in last few...,"{'neg': 0.071, 'neu': 0.782, 'pos': 0.147, 'co...",0.9972,pos
4,neg,my first press screening of 1998 and already i...,"{'neg': 0.091, 'neu': 0.817, 'pos': 0.093, 'co...",-0.2484,neg

In [72]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [74]:
accuracy_score(df['label'],df['comp_score'])

0.6357069143446853

In [84]:
print(classification_report(df['label'],df['comp_score']))

              precision    recall  f1-score   support

         neg       0.72      0.44      0.55       969
         pos       0.60      0.83      0.70       969

    accuracy                           0.64      1938
   macro avg       0.66      0.64      0.62      1938
weighted avg       0.66      0.64      0.62      1938

In [88]:
print(confusion_matrix(df['label'],df['comp_score']))

[[427 542]
 [164 805]]